--TASK1
USE Univer
SELECT PULPIT.PULPIT_NAME
	FROM PULPIT, FACULTY
	WHERE PULPIT.FACULTY = FACULTY.FACULTY 
	AND
	PULPIT.FACULTY IN (SELECT PROFESSION.FACULTY 
							FROM PROFESSION
							WHERE PROFESSION_NAME LIKE '%технолог%')

--TASK2
SELECT PULPIT.PULPIT_NAME
	FROM PULPIT 
	INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
	WHERE PULPIT.FACULTY IN (SELECT PROFESSION.FACULTY
								FROM PROFESSION
								WHERE PROFESSION_NAME LIKE '%технолог%')

--TASK3
SELECT DISTINCT PULPIT.PULPIT_NAME
	FROM PULPIT 
	INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
		WHERE PROFESSION.PROFESSION_NAME LIKE '%технолог%'

--TASK4
SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
	FROM AUDITORIUM T1
	WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY 
								FROM AUDITORIUM T2
								WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE
								ORDER BY AUDITORIUM_CAPACITY DESC)
	ORDER BY AUDITORIUM_CAPACITY DESC

--TASK5
SELECT FACULTY.FACULTY
	FROM FACULTY
	WHERE NOT EXISTS (SELECT *
					FROM PULPIT
					WHERE PULPIT.FACULTY = FACULTY.FACULTY)

--TASK6
SELECT TOP (1)
	(SELECT AVG(NOTE) FROM PROGRESS 
		WHERE PROGRESS.SUBJECT LIKE '%ОАиП%')[ОАиП],
	(SELECT AVG(NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT LIKE '%СУБД%')[СУБД],
	(SELECT AVG(NOTE) FROM PROGRESS 
		WHERE PROGRESS.SUBJECT LIKE '%БД%')[БД] 

--TASK7
SELECT NAME, BDAY
	FROM STUDENT
	WHERE BDAY >= ALL (SELECT BDAY FROM STUDENT
						WHERE NAME LIKE '%Ольга%')
	ORDER BY BDAY

SELECT * FROM STUDENT
	WHERE NAME LIKE '%Ольга%'
	ORDER BY BDAY

--TASK8
SELECT NAME, BDAY
	FROM STUDENT
	WHERE BDAY > ANY (SELECT BDAY FROM STUDENT
						WHERE NAME LIKE '%Ольга%')
	ORDER BY BDAY

SELECT * FROM STUDENT
	WHERE NAME LIKE '%Ольга%'
	ORDER BY BDAY
