USE Univer

--TASK1
SELECT F.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR, COUNT(*) AS AMOUNT
	FROM FACULTY AS F 
		INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE F.FACULTY LIKE '“Œ¬'
	GROUP BY F.FACULTY, G.PROFESSION, PR.SUBJECT WITH ROLLUP

--TASK2
SELECT F.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
	FROM FACULTY AS F 
		INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE F.FACULTY LIKE '“Œ¬'
	GROUP BY F.FACULTY, G.PROFESSION, PR.SUBJECT WITH CUBE

--TASK3
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '“Œ¬'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT
	UNION
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '’“Ë“'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT


SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '“Œ¬'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT
	UNION ALL
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '’“Ë“'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT

--TASK4
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '“Œ¬'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT
	INTERSECT
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '’“Ë“'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT

--TASK5
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '“Œ¬'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT
	EXCEPT
SELECT G.FACULTY, G.PROFESSION, PR.SUBJECT, ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVR , COUNT(*) AS AMOUNT
FROM GROUPS AS G
		INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
		INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
	WHERE G.FACULTY LIKE '’“Ë“'
	GROUP BY G.FACULTY, G.PROFESSION, PR.SUBJECT