USE Univer

--TASK1
SELECT AT.AUDITORIUM_TYPENAME,
	MAX(A.AUDITORIUM_CAPACITY) [MAX вместительность],
	MIN(A.AUDITORIUM_CAPACITY) [MIN вместительность],
	AVG(A.AUDITORIUM_CAPACITY) [AVG вместительность],
	SUM(A.AUDITORIUM_CAPACITY) [SUM вместительность],
	COUNT(*) [количество аудиторий]
	FROM AUDITORIUM_TYPE AS AT INNER JOIN AUDITORIUM AS A
	ON AT.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
		GROUP BY AT.AUDITORIUM_TYPENAME

--TASK3
SELECT * 
	FROM(SELECT CASE
			WHEN (p.NOTE in (4, 5)) THEN '4-5'
			WHEN (p.NOTE in (6, 7)) THEN '6-7'
			WHEN (p.NOTE in (8, 9)) THEN '8-9'
			WHEN (p.NOTE = 10) THEN '10'
			END [интервал],
		COUNT(*)[количество]
	FROM PROGRESS AS p
	GROUP BY CASE
		WHEN (p.NOTE in (4, 5)) THEN '4-5'
		WHEN (p.NOTE in (6, 7)) THEN '6-7'
		WHEN (p.NOTE in (8, 9)) THEN '8-9'
		WHEN (p.NOTE = 10) THEN '10'
		END
	) AS a
	ORDER BY CASE a.интервал 
		WHEN '4-5' THEN 4
		WHEN '6-7' THEN 3
		WHEN '8-9' THEN 2
		WHEN '10' THEN 1
		END

--TASK4
SELECT G.COURSE, G.PROFESSION, G.FACULTY,
		ROUND(AVG(CAST(PR.NOTE AS FLOAT)),2) [AVG_NOTE]
	FROM FACULTY AS F 
	INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
	INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
		GROUP BY G.COURSE, G.PROFESSION, G.FACULTY
		ORDER BY [AVG_NOTE] DESC

--TASK5
SELECT G.COURSE, G.PROFESSION, G.FACULTY,
		ROUND(AVG(CAST(PR.NOTE AS FLOAT)),2) [AVG_NOTE]
	FROM FACULTY AS F 
	INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
	INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
		WHERE PR.SUBJECT LIKE 'БД' OR PR.SUBJECT LIKE 'ОАиП'
		GROUP BY G.COURSE, G.PROFESSION, G.FACULTY
		ORDER BY [AVG_NOTE] DESC

--TASK6
SELECT G.PROFESSION, PR.SUBJECT,
	AVG(PR.NOTE) [AVG NOTE]
	FROM FACULTY AS F 
	INNER JOIN GROUPS AS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT AS ST ON G.IDGROUP = ST.IDGROUP
	INNER JOIN PROGRESS AS PR ON ST.IDSTUDENT = PR.IDSTUDENT
		WHERE F.FACULTY LIKE 'ТОВ'
		GROUP BY G.PROFESSION, PR.SUBJECT

--TASK7
SELECT P.SUBJECT, COUNT(*) [COUNT STUDENT]
	FROM PROGRESS AS P
	GROUP BY P.SUBJECT, P.NOTE
	HAVING P.NOTE IN (8,9)