--task 1
use Univer

SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM AS T1 INNER JOIN AUDITORIUM_TYPE AS T2 
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE;

--task 2
use Univer

SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM AS T1 INNER JOIN AUDITORIUM_TYPE AS T2 
	ON T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE 
	WHERE T2.AUDITORIUM_TYPENAME LIKE '%компьютер%';

--task 3
use Univer

SELECT ST.NAME AS [Имя Студента], FC.FACULTY_NAME AS Факультет, PL.PULPIT_NAME AS Кафедра, 
       PROF.PROFESSION_NAME AS Специальность, SB.SUBJECT_NAME AS Дисциплина,
       CASE
           WHEN (PROG.NOTE = 6) THEN 'шесть'
           WHEN (PROG.NOTE = 7) THEN 'семь'
           WHEN (PROG.NOTE = 8) THEN 'восемь'
       END AS [Оценка]
	FROM PROGRESS AS PROG 
	INNER JOIN STUDENT AS ST ON PROG.IDSTUDENT = ST.IDSTUDENT
	INNER JOIN GROUPS AS GR ON ST.IDGROUP = GR.IDGROUP
	INNER JOIN FACULTY AS FC ON GR.FACULTY = FC.FACULTY
	INNER JOIN PROFESSION AS PROF ON GR.PROFESSION = PROF.PROFESSION
	INNER JOIN SUBJECT AS SB ON PROG.SUBJECT = SB.SUBJECT
	INNER JOIN PULPIT AS PL ON SB.PULPIT = PL.PULPIT
	WHERE PROG.NOTE BETWEEN 6 AND 8
	ORDER BY PROG.NOTE DESC;

--task 4
use Univer

SELECT PL.PULPIT_NAME[Кафедра], isnull(TCH.TEACHER_NAME, '***')[Преподователь]
	FROM PULPIT AS PL LEFT OUTER JOIN TEACHER AS TCH
	ON PL.PULPIT = TCH.PULPIT

--task 5
use Univer

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT
	WHERE TEACHER.TEACHER IS NULL

use Univer

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT
	WHERE TEACHER.TEACHER IS NOT NULL

use Univer

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT

--task 6
use Univer

SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM AS T1 CROSS JOIN AUDITORIUM_TYPE AS T2 
	WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE;
